# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bart Ramaekers
email: bartramaekers99@gmail.com
description: >-
  My blog about the things I care to share.
  Reverse Engineering and broken code can and will be found here.
baseurl: ""
url: "https://bartramaekers.nl"
twitter_username: brtramaekers
github_username: deluze
show_excerpts: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed