source "https://rubygems.org"


gem "github-pages", "~> 231", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.0", :platforms => [:mingw, :x64_mingw, :mswin]

gem "kramdown-parser-gfm"

gem "webrick", "~> 1.8"
